#!/bin/zsh
macro=$1
exe=`basename $macro .cc`
echo $macro $exe
if [ ! -f $macro ];then
	echo "$macro not found"
	return -1
fi
g++ -o $exe $macro `root-config --cflags --libs` -lMinuit -Wno-deprecated
